In [4]:
import pandas as pd
import numpy as np
import scipy
import statsmodels.api as sm
import math
from math import sqrt
from statsmodels.formula.api import ols

from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

Prb1: 1-way ANOVA

In [2]:
sale = pd.read_excel('G:/IIT - nptel/Data Analytics with Python/data/salesman.xlsx')
sale

Salesman  Schedule 1  Schedule 2  Schedule 3
0         1          75          76          78
1         2          74          74          74
2         3          70          71          75
3         4          73          72          77
4         5          76          73          76
5         6          73          73          73

In [10]:
sale_data = pd.melt(sale.reset_index(), id_vars = ['Salesman'], value_vars = ['Schedule 1', 'Schedule 2', 'Schedule 3'])
sale_data.columns = ['Salesman', 'schedules', 'value']
sale_data

Salesman   schedules  value
0          1  Schedule 1     75
1          2  Schedule 1     74
2          3  Schedule 1     70
3          4  Schedule 1     73
4          5  Schedule 1     76
5          6  Schedule 1     73
6          1  Schedule 2     76
7          2  Schedule 2     74
8          3  Schedule 2     71
9          4  Schedule 2     72
10         5  Schedule 2     73
11         6  Schedule 2     73
12         1  Schedule 3     78
13         2  Schedule 3     74
14         3  Schedule 3     75
15         4  Schedule 3     77
16         5  Schedule 3     76
17         6  Schedule 3     73

In [11]:
sale_model = ols('value ~ C(schedules)', data = sale_data).fit()
sale_anova = sm.stats.anova_lm(sale_model, typ = 1)
sale_anova

df     sum_sq   mean_sq         F    PR(>F)
C(schedules)   2.0  19.111111  9.555556  2.662539  0.102434
Residual      15.0  53.833333  3.588889       NaN       NaN

Prb2: After Blocking - RBD

In [16]:
sale1 = sale

In [21]:
sale1_data = pd.melt(sale.reset_index(), id_vars = ['Salesman'], value_vars = ['Schedule 1', 'Schedule 2', 'Schedule 3'])
sale1_data.columns = ['blocks', 'schedules', 'value']
sale1_data

blocks   schedules  value
0        1  Schedule 1     75
1        2  Schedule 1     74
2        3  Schedule 1     70
3        4  Schedule 1     73
4        5  Schedule 1     76
5        6  Schedule 1     73
6        1  Schedule 2     76
7        2  Schedule 2     74
8        3  Schedule 2     71
9        4  Schedule 2     72
10       5  Schedule 2     73
11       6  Schedule 2     73
12       1  Schedule 3     78
13       2  Schedule 3     74
14       3  Schedule 3     75
15       4  Schedule 3     77
16       5  Schedule 3     76
17       6  Schedule 3     73

In [22]:
sale1_model = ols('value ~ C(blocks) + C(schedules)', data = sale1_data).fit()
sale1_anova = sm.stats.anova_lm(sale1_model, type = 1)
sale1_anova

df     sum_sq   mean_sq         F    PR(>F)
C(blocks)      5.0  34.277778  6.855556  3.505682  0.043290
C(schedules)   2.0  19.111111  9.555556  4.886364  0.033088
Residual      10.0  19.555556  1.955556       NaN       NaN

Prb7: R^2 value from Petrol Consumption Regression Analysis

In [5]:
petrl = pd.read_excel('G:/IIT - nptel/Data Analytics with Python/data/petrol.xlsx')
petrl

Miles travel  Petrol Consumption in litre
0            20                          1.0
1            45                          3.0
2            56                          5.0
3            34                          2.0
4            28                          1.6
5            49                          3.7

In [6]:
MT = petrl['Miles travel'] #x
PC = petrl['Petrol Consumption in litre'] #y

In [8]:
MT = sm.add_constant(MT) #x
model1 = sm.OLS(PC, MT)  #(y, x)
result1 = model1.fit()
print(result1.summary())

                                 OLS Regression Results                                
Dep. Variable:     Petrol Consumption in litre   R-squared:                       0.956
Model:                                     OLS   Adj. R-squared:                  0.945
Method:                          Least Squares   F-statistic:                     87.38
Date:                         Fri, 13 Mar 2020   Prob (F-statistic):           0.000729
Time:                                 23:35:07   Log-Likelihood:               -0.93716
No. Observations:                            6   AIC:                             5.874
Df Residuals:                                4   BIC:                             5.458
Df Model:                                    1                                         
Covariance Type:                     nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------

C:\Users\suvar\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  "samples were given." % int(n), ValueWarning)


In [1]:
0.1061/0.011

9.645454545454546

In [2]:
check = 2.776 * 0.011

In [3]:
(0.1061 - check, 0.1061 + check)

(0.075564, 0.136636)

In [36]:
avg = (20+45+56+34+28+49)/6

In [45]:
s = math.sqrt(((20 - avg)**2) + ((45 - avg)**2) + ((56 - avg)**2) + ((34 - avg)**2) + ((28 - avg)**2) + ((49 - avg)**2))
s

30.51775439532426

In [46]:
 math.sqrt(0.964) / s

0.03217258399723922

In [48]:
check = 3.182*0.032172583

(9.018 - check, 9.018 + check)

(8.915626840894001, 9.120373159106)

In [55]:
check = 2.776 * .964
9.018 - check, 9.018 + check

(6.3419360000000005, 11.694064000000001)

In [56]:
petrl = pd.read_excel('G:/IIT - nptel/Data Analytics with Python/data/petrol.xlsx')
data1 = petrl

In [57]:
x = data1['Miles travel'].values.reshape(-1, 1)
y = data1['Petrol Consumption in litre'].values.reshape(-1, 1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 88)


In [58]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((4, 1), (2, 1), (4, 1), (2, 1))

In [59]:
reg = LinearRegression()

In [60]:
reg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [61]:
reg.intercept_

array([-0.89476285])

In [62]:
reg.coef_

array([[0.08972332]])

In [63]:
y_predict = reg.predict(x_test)

In [64]:
y_predict

array([[4.12974308],
       [1.61749012]])

In [65]:
mean_squared_error(y_test, y_predict)

0.3788265029136528